spring:
  application:
    name: practice-entity-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/homework_entity_manager
    username: postgres
    password: Huy240419
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
server:
  port: 8081